FROM node:22 AS build
WORKDIR /app
COPY . .
RUN corepack enable && corepack prepare pnpm@latest-10 --activate
ENV CI=true
RUN pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm build

FROM nginx:1.25-alpine
COPY --from=build /app/dist /usr/share/nginx/html/secse-board
COPY nginx.conf /etc/nginx/nginx.conf
